# Generated by Django 4.1.3 on 2023-05-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='delete_url',
            field=models.URLField(blank=True),
        ),
    ]
