# Generated by Django 4.1.3 on 2023-06-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_post_delete_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='a',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
